// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAeGEuNXEQbYch5md8qPZFn5QSW64E1og4',
    appId: '1:106733356500:web:0940460c66f5901e148241',
    messagingSenderId: '106733356500',
    projectId: 'socialapp-ae93c',
    authDomain: 'socialapp-ae93c.firebaseapp.com',
    storageBucket: 'socialapp-ae93c.appspot.com',
    measurementId: 'G-FSCKGGKQC8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8BKe2NK7kXcPrMkVmr1-qXpsmUbW_6vQ',
    appId: '1:106733356500:android:50dfdb44274b7497148241',
    messagingSenderId: '106733356500',
    projectId: 'socialapp-ae93c',
    storageBucket: 'socialapp-ae93c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBHNMITMnISUvoxIETrNMk0V4-XyPauux8',
    appId: '1:106733356500:ios:a55f79e284589e59148241',
    messagingSenderId: '106733356500',
    projectId: 'socialapp-ae93c',
    storageBucket: 'socialapp-ae93c.appspot.com',
    iosBundleId: 'com.application.socialapp.socialApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAeGEuNXEQbYch5md8qPZFn5QSW64E1og4',
    appId: '1:106733356500:web:7d40b1fefb8c5a95148241',
    messagingSenderId: '106733356500',
    projectId: 'socialapp-ae93c',
    authDomain: 'socialapp-ae93c.firebaseapp.com',
    storageBucket: 'socialapp-ae93c.appspot.com',
    measurementId: 'G-4HXJ7Y5BHL',
  );
}
